project:
  type: website
  output-dir: docs

website:
  title: "Min Sung Seo"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Papers"
        href: papers.qmd
      - icon: github
        href: https://github.com/msungseo
      - icon: envelope
        href: mailto:mks7518@psu.edu

format:
  html:
    theme: flatly
    css: styles.css
    toc: false