project:
  type: website
  output-dir: docs
  resources:
    - cv/
    - img/

website:
  title: "Min Sung Seo"
  site-url: https://msungseo.github.io
  description: "Cognitive neuroscience of memory and aging"
  open-graph: true
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: papers.qmd
      - text: "CV"
        href: cv/CV_Seo_071126.pdf
        target: _blank
      - icon: github
        href: https://github.com/msungseo
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=JofjEW0AAAAJ&hl=en
      - icon: envelope
        href: mailto:mks7518@psu.edu

format:
  html:
    theme: flatly
    css: styles.css
    toc: false