---
title: ""
---

## Bio

I am a postdoctoral scholar in Dr. Nancy Dennis's [Cognitive Aging and Neuroscience Laboratory (CANLAB)](https://canlab.la.psu.edu/) at Penn State, University Park, working on the neural correlates of episodic memory and aging. My research uses behavioral and neuroimaging methods to understand how memory changes across the lifespan.

I completed my PhD in Cognitive Psychology at the University of North Carolina at Chapel Hill (2025) and my BS in Psychology, Neuroscience Option, at Penn State, University Park (2020).

Outside of research, I play tennis and golf, and am patiently waiting to outlive the ending of One Piece.

---

## Education

**PhD, Cognitive Psychology**
The University of North Carolina at Chapel Hill, 2025

**MA, Cognitive Psychology**
The University of North Carolina at Chapel Hill, 2023

**BS, Psychology (Neuroscience Option)**
The Pennsylvania State University at University Park, 2020

---

## CV

You can download my full CV [here](cv/CV_Seo_082525.pdf).